version: '3.8'

services:
  ai_agent:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../models:/app/models
      - ../logs:/app/logs
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: 